name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # A cada 12 horas (00:00 e 12:00)
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: pabllohyanferreira
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica na branch "output"
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
